POST http://localhost:8080/events
# Headers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM0NTUzMTMyLCJ1c2VySWQiOjB9.K7gzLd3B8gIVIPdvEBKx57_JtBuj4Jjx3EXEXOwaMS4

# Data
{
    "name": "Tomorrowland (Updated)",
    "description": "A big event in Belgium",
    "location": "Belgium Hills",
    "dateTime": "2025-01-01T221:30:00.000Z"
}